---
- name: Upgrade LMDE 6 to LMDE 7
  hosts: all
  become: yes
  tasks:

    - name: Update package lists
      apt:
        update_cache: yes
        cache_valid_time: 3600  # 1 hour

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Remove unnecessary packages
      apt:
        autoremove: yes
        autoclean: yes

    - name: Update package lists for LMDE 7
      apt:
        update_cache: yes

    - name: Perform full upgrade to LMDE 7
      apt:
        upgrade: dist

    - name: Clean up after the upgrade
      apt:
        autoremove: yes
        autoclean: yes

    - name: Reboot the system
      reboot:
        msg: "Rebooting the system to complete upgrade"
        reconnect_timeout: 30

