---
- name: Upgrade LMDE 6 to LMDE 7
  hosts: all
  become: yes
  tasks:

    - name: Update package lists
      apt:
        update_cache: yes
        cache_valid_time: 3600  # 1 hour

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Remove unnecessary packages
      apt:
        autoremove: yes
        autoclean: yes

    
